# Generated by Django 5.0.6 on 2024-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredientType',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
