# Generated by Django 5.0.6 on 2024-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_ingredienttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientType',
            field=models.CharField(blank=True, choices=[('Lactate, brânză și ouă', 'Lactate, brânză și ouă'), ('Legume și fructe', 'Legume și fructe'), ('Carne și pește', 'Carne și pește'), ('Cereale, făinoase, nuci', 'Cereale, făinoase, nuci'), ('Condimente și Uleiuri', 'Condimente și Uleiuri'), ('Diverse', 'Diverse')], default='Diverse', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measure',
            field=models.CharField(choices=[('g', 'Grame'), ('kg', 'Kilograme'), ('ml', 'Mililitri'), ('l', 'Litri'), ('tsp', 'Lingurițe'), ('tbsp', 'Linguri'), ('cup', 'Căni'), ('piece', 'Bucăți')], default='g', max_length=255),
        ),
    ]
