# Generated by Django 5.0.6 on 2024-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('ingredient', models.TextField(max_length=1000)),
                ('preparation', models.TextField(max_length=2000)),
                ('nutritional_value', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('proteins', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
                ('fibers', models.IntegerField(default=0)),
                ('mealType', models.IntegerField(default=1)),
                ('preparationTime', models.IntegerField(default=0)),
            ],
        ),
    ]
