# Generated by Django 5.0.6 on 2024-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_antibloating_meal_anticonstipation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
