# Generated by Django 5.0.6 on 2024-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dayOfTheWeek',
            field=models.CharField(choices=[('Luni', 'Luni'), ('Marti', 'Marti'), ('Miercuri', 'Miercuri'), ('Joi', 'Joi'), ('Vineri', 'Vineri'), ('Sambata', 'Sambata'), ('Duminica', 'Duminica')], default='Luni', max_length=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
