# Generated by Django 5.0.6 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_dayoftheweek_meal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(default='No Description', max_length=1000),
        ),
    ]
