# Generated by Django 5.0.6 on 2024-05-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('meals', '0008_alter_meal_mealtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredient',
            field=models.ManyToManyField(related_name='meals', to='ingredients.ingredient'),
        ),
    ]
