# Generated by Django 5.0.6 on 2024-05-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('meals', '0009_remove_meal_ingredient_meal_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredients', to='ingredients.ingredient'),
        ),
    ]
