# Generated by Django 5.0.6 on 2024-05-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('meals', '0010_alter_meal_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredient',
            field=models.ManyToManyField(to='ingredients.ingredient'),
        ),
    ]
