# Generated by Django 5.0.6 on 2024-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_meal_weeknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
