# Generated by Django 5.0.6 on 2024-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_remove_meal_ingredient_meal_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
