# Generated by Django 5.0.6 on 2024-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0003_rename_usual_program_user_dailyschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dailySchedule',
            field=models.CharField(choices=[('Timp de lucru complet la birou', 'Timp de lucru complet la birou'), ('Lucrez de acasă', 'Lucrez de acasă'), (' Program variabil', 'Program variabil'), ('Lucrez in schimburi', 'Lucrez in schimburi')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='digestion',
            field=models.CharField(choices=[('Anti-Balonare', 'Anti-Balonare'), ('Anti-Constipație', 'Anti-Constipație')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='foodPreferences',
            field=models.CharField(choices=[('Omnivor', 'Omnivor'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Pescaterian', 'Pescaterian')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Bărbat ', 'Bărbat '), ('Femeie ', 'Femeie ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='generalMood',
            field=models.CharField(choices=[('Anti-Stres', 'Anti-Stres'), ('NIVELDEENERGIEMAIRIDICAT', 'Nivel de energie mai ridicat')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='hormonal',
            field=models.CharField(choices=[('Îmbunătățire simptome ovare polichistice', 'Îmbunătățire simptome ovare polichistice'), ('Îmbunătățire simptome endometrioză', 'Îmbunătățire simptome endometrioză')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='intolerancies',
            field=models.CharField(choices=[('Fără lactoză', 'Fără lactoză'), ('Fără gluten', 'Fără gluten')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='mainObjective',
            field=models.CharField(choices=[('Stare generală de bine', 'Stare generală de bine'), ('Digestie îmbunătățită', 'Digestie îmbunătățită'), ('Echilibru hormonal', 'Echilibru hormonal'), ('Intolerante ', 'Intolerante ')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='restrictionDiet',
            field=models.CharField(choices=[('Da', 'Da'), ('Nu', 'Nu')], max_length=40),
        ),
    ]
