# Generated by Django 5.0.6 on 2024-05-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0004_alter_user_dailyschedule_alter_user_digestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Bărbat', 'Bărbat'), ('Femeie', 'Femeie')], max_length=20),
        ),
    ]
