# Generated by Django 5.0.6 on 2024-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='restrictionDiet',
        ),
    ]
