# Generated by Django 5.0.6 on 2024-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0007_user_excludefoods_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digestion',
            field=models.CharField(blank=True, choices=[('Anti-Balonare', 'Anti-Balonare'), ('Anti-Constipație', 'Anti-Constipație')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='excludedFoods',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='hormonal',
            field=models.CharField(blank=True, choices=[('Îmbunătățire simptome ovare polichistice', 'Îmbunătățire simptome ovare polichistice'), ('Îmbunătățire simptome endometrioză', 'Îmbunătățire simptome endometrioză')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='intolerancies',
            field=models.CharField(blank=True, choices=[('Fără lactoză', 'Fără lactoză'), ('Fără gluten', 'Fără gluten')], max_length=40),
        ),
    ]
