# Generated by Django 5.0.6 on 2024-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0008_alter_user_digestion_alter_user_excludedfoods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='digestion',
            field=models.CharField(blank=True, choices=[('Anti-Balonare', 'Anti-Balonare'), ('Anti-Constipație', 'Anti-Constipație'), ('', '')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='generalMood',
            field=models.CharField(choices=[('Anti-Stres', 'Anti-Stres'), ('NIVELDEENERGIEMAIRIDICAT', 'Nivel de energie mai ridicat'), ('', '')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='hormonal',
            field=models.CharField(blank=True, choices=[('Îmbunătățire simptome ovare polichistice', 'Îmbunătățire simptome ovare polichistice'), ('Îmbunătățire simptome endometrioză', 'Îmbunătățire simptome endometrioză'), ('', '')], max_length=40),
        ),
    ]
