# Generated by Django 5.0.6 on 2024-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0009_alter_user_digestion_alter_user_generalmood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='generalMood',
            field=models.CharField(choices=[('Anti-Stres', 'Anti-Stres'), ('Nivel de energie mai ridicat', 'Nivel de energie mai ridicat'), ('', '')], max_length=40),
        ),
    ]
