# Generated by Django 5.0.6 on 2024-05-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0010_alter_user_generalmood'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='antiBloatingAnti-Balonare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='antiConstipationAnti-Constipație',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='antiStressAnti-Stres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='energyLevelHigherNiveldeenergiemairidicat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='glutenFreeFărăgluten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='improvementEndometriosisÎmbunătățiresimptomeendometrioză',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='improvementPCOSÎmbunătățiresimptomeovarepolichistice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lactoseFreeFărălactoză',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='dailySchedule',
            field=models.CharField(choices=[('Timp de lucru complet la birou', 'Timp de lucru complet la birou'), ('Lucrez de acasă', 'Lucrez de acasă'), ('Program variabil', 'Program variabil'), ('Lucrez in schimburi', 'Lucrez in schimburi')], max_length=40),
        ),
    ]
