# Generated by Django 5.0.6 on 2024-05-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0011_user_antibloatinganti_balonare_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='antiBloatingAnti-Balonare',
            new_name='antiBloating',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='antiConstipationAnti-Constipație',
            new_name='antiConstipation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='antiStressAnti-Stres',
            new_name='antiStress',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='energyLevelHigherNiveldeenergiemairidicat',
            new_name='energyLevelHigher',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='glutenFreeFărăgluten',
            new_name='glutenFree',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='improvementEndometriosisÎmbunătățiresimptomeendometrioză',
            new_name='improvementEndometriosis',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='improvementPCOSÎmbunătățiresimptomeovarepolichistice',
            new_name='improvementPCOS',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lactoseFreeFărălactoză',
            new_name='lactoseFree',
        ),
    ]
