# Generated by Django 5.0.6 on 2024-06-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSystem', '0013_alter_user_generalmood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dailySchedule',
            field=models.CharField(choices=[('Timp de lucru complet la birou', 'Timp de lucru complet la birou'), ('Lucrez de acasă', 'Lucrez de acasă'), ('Program variabil', 'Program variabil'), ('Lucrez în schimburi', 'Lucrez în schimburi')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='mainObjective',
            field=models.CharField(choices=[('Stare generală de bine', 'Stare generală de bine'), ('Digestie îmbunătățită', 'Digestie îmbunătățită'), ('Echilibru hormonal', 'Echilibru hormonal'), ('Intolerante', 'Intolerante')], max_length=40),
        ),
    ]
